from pathlib import Path

FPS: int = 60
WIDTH: int = 600
HEIGHT: int = 600
BOARD_SIZE: int = 8
PIECE_SET = "alpha"

HEIGHT_PER_SQUARE: int = HEIGHT // BOARD_SIZE
WIDTH_PER_SQUARE: int = WIDTH // BOARD_SIZE

FEN_STARTING_POSITION: str = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
FEN_VALID_PIECE_CHARACTERS: str = "rnbqkpRNBQKP"
FEN_VALID_EMPTY_SQUARE_CHARACTERS: str = "12345678"
FEN_VALID_BOARD_CHARACTERS: str = FEN_VALID_PIECE_CHARACTERS + FEN_VALID_EMPTY_SQUARE_CHARACTERS

ASSETS_DIRECTORY: Path = Path(__file__).parent.parent.parent / "assets"
ASSETS_PIECES_DIRECTORY: Path = ASSETS_DIRECTORY / "pieces"